### ISSUE TITLE
Infografía Librerías

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/infografia-de-las-librerias-Ferch0419#2]
[Librerías Infografía Fernando Miguel López.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-Ferch0419/files/6308254/Librerias.Infografia.Fernando.Miguel.Lopez.pdf)

**Comment by javiern-778** [comment]
un excelente trabajo tiene 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
